### ISSUE TITLE
Don't use inter

### ISSUE THREAD

**Issue by damywise** [Ali-Hussein-dev/KamousAI#31]
Sorry but I just don't like how it looks.. 
Feels very out of place
![image](https://github.com/Ali-Hussein-dev/KamousAI/assets/25608913/4c778ee7-36dc-445b-87a0-b8c474e750e1)

**Comment by Ali-Hussein-dev** [comment]
do you mean the color scheme? @damywise

**Comment by damywise** [comment]
Sorry I wasn't clear. It's the font.
