### ISSUE TITLE
Please rethink the color scheme

### ISSUE THREAD

**Issue by damywise** [Ali-Hussein-dev/KamousAI#33]
The previous one seem to follow a certain guideline.
Why has the new one suddenly become very contrast?
Before: Nice, calm blue
![image](https://github.com/Ali-Hussein-dev/KamousAI/assets/25608913/2dac6766-a32d-4e12-92c6-f512f7a78d81)
After: Some blue with very contrasting gray/sand/orange?
![image](https://github.com/Ali-Hussein-dev/KamousAI/assets/25608913/20272574-1552-48e5-ba0c-8ba1774dcf71)

**Comment by Ali-Hussein-dev** [comment]
will reconsider it.
