### ISSUE TITLE
Grammar Corrector: With explanation doesnt work

### ISSUE THREAD

**Issue by damywise** [Ali-Hussein-dev/KamousAI#58]
Heya, the 'with explanation' button in the Grammar Corrector doesn't seem to work most of the time. The result of with and without toggling it is identical.

**Comment by Ali-Hussein-dev** [comment]
This is due to the LLM, the outcomes are inconsistent. I modified the prompt, but feel free to propose an alternative phrasing.

You can find the prompt here `app/api/grammar-checker/route.ts`

**Comment by damywise** [comment]
Hmm, it seems to still not work as expected. However, I noticed a change: The incorrect words are bold (with explanations enabled).

I'll make a pull request with experimental prompts if that's okay with you, since I don't have a subscription to gpt.
